### ISSUE TITLE
Greater Than or Less Than Filters

### ISSUE THREAD

**Issue by MamlukiSn** [yii2mod/yii2-array-query#1]
Hi,

Thanks for the extension. Does this provide for greater then or less than filters,

Regards,

**Comment by ihorchepurnyi** [comment]
Hi,
I have added new filters, please update your package.

Now, you can use the following filters:

```php
$query->where(['>','id', 1]);
$query->where(['<','id', 1]);
$query->where(['>=','id', 1]);
$query->where(['<=','id', 1]);
$query->where(['!=','id', 1]);
$query->where(['==','id', 1]);
```
