### ISSUE TITLE
PHP 7.2 compatibility

### ISSUE THREAD

**Issue by iqbalhs** [yii2mod/yii2-array-query#2]
Hello, thank you for this awesome extension. It helps me out a lot!

However I want to report that this does not compatible with PHP version > 7.2 due to change to PHP's `count()` function throws a warning in case a scalar or non-countable object is passed. 

 https://github.com/yii2mod/yii2-array-query/blob/0a82e9a1eebc0a4001d1f9c6f67958a88ce9191e/QueryProcessor.php#L335

Perhaps should check if `$column` is an array instead or cast variable `$column` to array (which I did to quick fix this in my project).

**Comment by ihorchepurnyi** [comment]
Hi @iqbalhs, could you please create a pull request for this issue>
